FROM node:20-alpine

# Install build dependencies for native modules
RUN apk add --no-cache make gcc g++ python3

WORKDIR /app

COPY package.json yarn.lock ./
COPY .yarnrc.yml .yarnrc.yml

# Public app env needed at build-time for Next.js prerendering
ARG NEXT_PUBLIC_BASE_API_URL
ARG LANGSMITH_API_KEY
ARG NEXT_PUBLIC_USE_LANGSMITH_AUTH
ARG NEXT_PUBLIC_DEPLOYMENTS
ARG NEXT_PUBLIC_RAG_API_URL
ARG INTERNAL_RAG_URL
ARG NEXT_PUBLIC_MCP_SERVER_URL
ARG NEXT_PUBLIC_MCP_SERVER_INTERNAL_URL
ARG NEXT_PUBLIC_MCP_AUTH_REQUIRED
ARG NEXT_PUBLIC_GOOGLE_AUTH_DISABLED
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV NEXT_PUBLIC_BASE_API_URL=$NEXT_PUBLIC_BASE_API_URL
ENV LANGSMITH_API_KEY=$LANGSMITH_API_KEY
ENV NEXT_PUBLIC_USE_LANGSMITH_AUTH=$NEXT_PUBLIC_USE_LANGSMITH_AUTH
ENV NEXT_PUBLIC_DEPLOYMENTS=$NEXT_PUBLIC_DEPLOYMENTS
ENV NEXT_PUBLIC_RAG_API_URL=$NEXT_PUBLIC_RAG_API_URL
ENV INTERNAL_RAG_URL=$INTERNAL_RAG_URL
ENV NEXT_PUBLIC_MCP_SERVER_URL=$NEXT_PUBLIC_MCP_SERVER_URL
ENV NEXT_PUBLIC_MCP_SERVER_INTERNAL_URL=$NEXT_PUBLIC_MCP_SERVER_INTERNAL_URL
ENV NEXT_PUBLIC_MCP_AUTH_REQUIRED=$NEXT_PUBLIC_MCP_AUTH_REQUIRED
ENV NEXT_PUBLIC_GOOGLE_AUTH_DISABLED=$NEXT_PUBLIC_GOOGLE_AUTH_DISABLED
ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY

COPY apps/ ./apps/
# COPY packages/ ./packages/
COPY turbo.json ./

RUN corepack enable && corepack prepare yarn@3.5.1 --activate
RUN yarn install --immutable

COPY . .

ENV NODE_ENV=production

# Build the web workspace
RUN yarn workspace @open-agent-platform/web build

EXPOSE 3000

CMD ["yarn", "workspace", "@open-agent-platform/web", "start"]
